version: "3"

run: when_changed

vars:
  BIN: "bin/shimdns"

env:
  CGO_ENABLED: 0

tasks:
  ### run

  run:
    deps: [build]
    cmds:
      - ./{{ .BIN }} {{.CLI_ARGS}}

  ### build

  build:
    deps: [templ]
    sources:
      - "**/*.go"
      - "**/*.templ"

    cmds:
      - go build -o {{ .BIN }} .

  build-all:
    deps: [templ]
    sources:
      - "**/*.go"
      - "**/*.templ"

    cmds:
      - for:
          matrix:
            OS: ['windows', 'linux', 'darwin']
            ARCH: ['amd64', 'arm64']

        cmd:
          GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} go build -o bin/shimdns-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}{{ if eq .ITEM.OS "windows" }}.exe{{ end }} .

  templ:
    sources:
      - "**/*.templ"

    cmds:
      - go tool templ generate

  ### tests

  test:
    deps: [templ]
    cmds:
      - go test -timeout 3m ./...
      - go tool errcheck ./...
      - go tool ineffassign ./...
