version: "3"

run: when_changed

vars:
  BIN: "bin/shimdns"

env:
  CGO_ENABLED: 0

tasks:
  ### run

  run:
    deps: [build]
    cmds:
      - ./{{ .BIN }} {{.CLI_ARGS}}

  ### build

  build:
    deps: [templ]
    sources:
      - "**/*.go"
      - "**/*.templ"

    cmds:
      - go build -o {{ .BIN }} .

  build-ci:
    deps: [templ]
    sources:
      - "**/*.go"
      - "**/*.templ"

    cmds:
      - GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/shimdns .

  templ:
    sources:
      - "**/*.templ"

    cmds:
      - go tool templ generate

  ### tests

  test:
    deps: [templ]
    cmds:
      - go test -timeout 3m ./...
      - go tool errcheck ./...
      - go tool ineffassign ./...
